name: CI Pipeline - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-main:
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      git_branch          : 'main'
      release_type        : 'major'
      should_increment_tag: true
      target_url          : 'https://send.sgraph.ai'
    secrets: inherit
